export const PROPOSALS = [
  {
    id: 1,
    proposalNo: '2022/0037',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Price Lead',
    status: 'Ongoing',
    action:{view:0, edit:1, download:0, delete:0}
  },
  {
    id: 2,
    proposalNo: '2022/0034',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 2,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Price Lead',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 3,
    proposalNo: '2022/0028',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 1,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'Returned',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 4,
    proposalNo: '2022/0026',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 4,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'Rejected',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 5,
    proposalNo: '2022/0024',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'Approved',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 6,
    proposalNo: '2022/0019',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 7,
    proposalNo: '2022/0017',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 8,
    proposalNo: '2021/0019',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 9,
    proposalNo: '2021/0017',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 10,
    proposalNo: '2021/0015',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  {
    id: 11,
    proposalNo: '2021/0010',
    proposalTitle: 'Evrysdi SMA',
    productName: 'Product Title',
    proposalStatus: 3,
    CreateBy: 'Dev Masuria',
    CreatedAt: '07/05/2022',
    propsalStage: 'Cluster Head',
    status: 'NA',
    action:{view:1, edit:1, download:0, delete:0}
  },
  
];
